trigger:
- none

pool:
  name: Nayak-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- powershell: |
    Write-Host "=================="
    Write-Host "Terraform Version"
    Write-Host "=================="

    terraform version

    Write-Host "=================="
    Write-Host "Where Terraform"
    Write-Host "=================="

    where.exe terraform