trigger: none

pool:
  name: KK-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.15.8'

- powershell: |
    terraform version

    cd "$(Build.SourcesDirectory)\environments\dev"

    terraform init
  displayName: 'Terraform Init using PowerShell'